name: draw keymap

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/doc.yml"
      - "docs/keymap/**/keymap_drawer.yaml"
      - "config/**/*.keymap"
      - "config/**/*.dtsi"

jobs:
  draw_temper:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "doc: updated keymap for temper"
      keymap_patterns: "config/temper/*.keymap"
      config_path: "docs/keymap/temper/keymap_drawer.yaml"  # config file, ignored if it does not exist
      output_folder: "docs/keymap/temper"
      parse_args: "temper:'-c 10'"                         # map of extra args to pass to `keymap parse`
      draw_args: "temper:'-k chocofi'"   # map of extra args to pass to `keymap draw`

  draw_charybdis:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "doc: updated keymap for charybdis"
      keymap_patterns: "config/charybdis/*.keymap"
      config_path: "docs/keymap/charybdis/keymap_drawer.yaml"
      output_folder: "docs/keymap/charybdis"
      parse_args: ""
      draw_args: "charybdis:'-j config/charybdis/info.json -l five_column_transform'"
